### ISSUE TITLE
Auto-split permanently deactivated

### ISSUE THREAD

**Issue by worp1900** [Ellpeck/ActuallyAdditions#567]
The auto split feature in the double crusher and double furnace seems to have a problem (unless I am missing a hint somewhere).

I had the auto-split working for a couple of days, then I broke them down and moved them to construct a better setup. Since then the auto-split button is read and, when clicked, doesn't switch to on anymore.

See screenshot: https://owncloud.mindworp.de/index.php/s/i36luCnjWRvF4H9

**Comment by Ellpeck** [comment]
Try re-connecting, if you didn't do that yet. Sometimes packets for GUIs aren't properly being sent, but it happens very rarely and seems to be some sort of Forge bug.

**Comment by Ellpeck** [comment]
If that doesn't help, break the block again and turn on F3+H (plus the advanced info in the config), and then press Shift and Ctrl over the picked up items (so that the NBT part is visible) and take a screenshot :)

**Comment by worp1900** [comment]
Thx 4 getting back to me so fast. Very much appreciated :)
I put the two screenshots in the folder:
https://owncloud.mindworp.de/index.php/s/T7MqcUaETA96j3K

I couldn't get the Ctrl+Shift to work for me. It won't display any more detail than the "NBT: 1 tag(s)" part.

You said something about "advanced info in the config". I am assuming this means server config? Which option is that concretely? As a quick google didn't turn up the name.
(It's an online server, but I have control over it. So would be possible.)

**Comment by Ellpeck** [comment]
In your actually additions client config.

**Comment by worp1900** [comment]
Done, the screenshots were added to the folder again:
https://owncloud.mindworp.de/index.php/s/T7MqcUaETA96j3K

**Comment by Ellpeck** [comment]
You are pressing shift in neither of them like I told you to :v

**Comment by worp1900** [comment]
Apologies. Check the folder. Shift key pressed this time.

**Comment by Ellpeck** [comment]
Yea, this doesn't make any sense :v
So reconnecting doesn't fix this? Which version are you on?

**Comment by worp1900** [comment]
Sadly not.
Actually Additions: 1.10.2-r88
Minecraft: 1.10.2

**Comment by worp1900** [comment]
I should add that it's not a big hassle. "Things not going as fast as they could be" is a luxury problem after all. So don't wrap your friday night around it :D

**Comment by Ellpeck** [comment]
Man, your mod version is way outdated O_O
Update and see if that fixes it :P

**Comment by worp1900** [comment]
Will check that out on a local run. updating the server is probably going to be a problem, as everyone is running with the package provided by curse client.
But you're right. I should do that first and then see.

I guess we can close this for oudated.

In any case: I appreciate your time and fast response. Haven't had a direct talk with someone on github in a while!

**Comment by Ellpeck** [comment]
Heh, thanks :P
I will close this for now as I can't reproduce it either. If this happens again, just open this back up :)
